export const usersData= [
    {
      name: 'Jan',
      "Active Users": 1000,
    },
    {
      name: 'Feb',
      "Active Users": 1200,
    },
    {
        name: 'Mar',
        "Active Users": 1150,
    },
    {
        name: 'Apr',
        "Active Users": 1500,
    },
    {
        name: 'May',
        "Active Users": 1450,
    },
    {
        name: 'Jun',
        "Active Users": 1450,
    },
    {
        name: 'Jul',
        "Active Users": 1780,
    },
    {
        name: 'Aug',
        "Active Users": 1820,
    },
    {
        name: 'Sep',
        "Active Users": 1830,
    },
    {
        name: 'Oct',
        "Active Users": 1900,
    },
    {
        name: 'Nov',
        "Active Users": 2200,
    },
    {
        name: 'Dec',
        "Active Users": 2800,
    },
   
  ];

  export const productsData= [
    {
      name: 'Jan',
      "Sales": 1000,
    },
    {
      name: 'Feb',
      "Sales": 1200,
    },
    {
        name: 'Mar',
        "Sales": 1150,
    },
    
  ];

 export const usersRows = [
    { id: 1, username: 'Jon Snow', 
      avatar:"http://placekitten.com/g/300/300", 
      email:"JonS@gmail.com", 
      status:"active", 
      transaction:"Eur 100"},
      { id: 2, username: 'Jon Snow', 
      avatar:"http://placekitten.com/g/300/300", 
      email:"JonS@gmail.com", 
      status:"active", 
      transaction:"Eur 100"},
      { id: 3, username: 'Jon Snow', 
      avatar:"http://placekitten.com/g/300/300", 
      email:"JonS@gmail.com", 
      status:"active", 
      transaction:"Eur 100"},
      { id: 4, username: 'Jon Snow', 
      avatar:"http://placekitten.com/g/300/300", 
      email:"JonS@gmail.com", 
      status:"active", 
      transaction:"Eur 100"},
      { id: 5, username: 'Jon Snow', 
      avatar:"http://placekitten.com/g/300/300", 
      email:"JonS@gmail.com", 
      status:"active", 
      transaction:"Eur 100"},
      { id: 6, username: 'Jon Snow', 
      avatar:"http://placekitten.com/g/300/300", 
      email:"JonS@gmail.com", 
      status:"active", 
      transaction:"Eur 100"},
      { id: 7, username: 'Jon Snow', 
      avatar:"http://placekitten.com/g/300/300", 
      email:"JonS@gmail.com", 
      status:"active", 
      transaction:"Eur 100"},
      { id: 8, username: 'Jon Snow', 
      avatar:"http://placekitten.com/g/300/300", 
      email:"JonS@gmail.com", 
      status:"active", 
      transaction:"Eur 100"},
      { id: 9, username: 'Jon Snow', 
      avatar:"http://placekitten.com/g/300/300", 
      email:"JonS@gmail.com", 
      status:"active", 
      transaction:"Eur 100"},
      { id: 10, username: 'Jon Snow', 
      avatar:"http://placekitten.com/g/300/300", 
      email:"JonS@gmail.com", 
      status:"active", 
      transaction:"Eur 100"},
    
  ];

  export const productsRows = [
    { id: 1, name: 'Computer', 
      img:"https://images.pexels.com/photos/812264/pexels-photo-812264.jpeg?cs=srgb&dl=pexels-tuur-tisseghem-812264.jpg&fm=jpg", 
      stock:999, 
      status:"active", 
      price:"Eur 100"},
      { id: 2, name: 'Computer', 
      img:"https://images.pexels.com/photos/812264/pexels-photo-812264.jpeg?cs=srgb&dl=pexels-tuur-tisseghem-812264.jpg&fm=jpg", 
      stock:999, 
      status:"active", 
      price:"Eur 100"},
      { id: 3, name: 'Computer', 
      img:"https://images.pexels.com/photos/812264/pexels-photo-812264.jpeg?cs=srgb&dl=pexels-tuur-tisseghem-812264.jpg&fm=jpg", 
      stock:999, 
      status:"active", 
      price:"Eur 100"},
      { id: 4, name: 'Computer', 
      img:"https://images.pexels.com/photos/812264/pexels-photo-812264.jpeg?cs=srgb&dl=pexels-tuur-tisseghem-812264.jpg&fm=jpg", 
      stock:999, 
      status:"active", 
      price:"Eur 100"},
      { id: 5, name: 'Computer', 
      img:"https://images.pexels.com/photos/812264/pexels-photo-812264.jpeg?cs=srgb&dl=pexels-tuur-tisseghem-812264.jpg&fm=jpg", 
      stock:999, 
      status:"active", 
      price:"Eur 100"},
      { id: 6, name: 'Computer', 
      img:"https://images.pexels.com/photos/812264/pexels-photo-812264.jpeg?cs=srgb&dl=pexels-tuur-tisseghem-812264.jpg&fm=jpg", 
      stock:999, 
      status:"active", 
      price:"Eur 100"},
      { id: 7, name: 'Computer', 
      img:"https://images.pexels.com/photos/812264/pexels-photo-812264.jpeg?cs=srgb&dl=pexels-tuur-tisseghem-812264.jpg&fm=jpg", 
      stock:999, 
      status:"active", 
      price:"Eur 100"},
      { id: 8, name: 'Computer', 
      img:"https://images.pexels.com/photos/812264/pexels-photo-812264.jpeg?cs=srgb&dl=pexels-tuur-tisseghem-812264.jpg&fm=jpg", 
      stock:999, 
      status:"active", 
      price:"Eur 100"},
      { id: 9, name: 'Computer', 
      img:"https://images.pexels.com/photos/812264/pexels-photo-812264.jpeg?cs=srgb&dl=pexels-tuur-tisseghem-812264.jpg&fm=jpg", 
      stock:999, 
      status:"active", 
      price:"Eur 100"},
      { id: 10, name: 'Computer', 
      img:"https://images.pexels.com/photos/812264/pexels-photo-812264.jpeg?cs=srgb&dl=pexels-tuur-tisseghem-812264.jpg&fm=jpg", 
      stock:999, 
      status:"active", 
      price:"Eur 100"},
    
  ];